# Generated by Django 5.1.7 on 2025-03-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titular', models.CharField(max_length=100)),
                ('numero_cartao', models.CharField(max_length=16)),
                ('data_validade', models.CharField(max_length=5)),
                ('codigo_seguranca', models.CharField(max_length=3)),
            ],
        ),
    ]
