# Generated by Django 5.1.7 on 2025-03-26 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0002_cartao_senha_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
