# Generated by Django 5.1.7 on 2025-04-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0003_cartao_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartao',
            name='data_criacao',
        ),
    ]
