# Generated by Django 5.1.7 on 2025-04-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartao', '0004_remove_cartao_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='senha_cartao',
            field=models.CharField(max_length=100),
        ),
    ]
